// ============================================================================
// Public DNS Zone Module
// ============================================================================
// Creates Azure DNS zone for public domain resolution
// SOA and NS records are auto-generated by Azure

@description('DNS zone name (e.g., poc.valero.com)')
param zoneName string

@description('Resource tags')
param tags object = {}

// ============================================================================
// RESOURCES
// ============================================================================

resource dnsZone 'Microsoft.Network/dnsZones@2018-05-01' = {
  name: zoneName
  location: 'global'
  tags: tags
  properties: {
    zoneType: 'Public'
  }
}

// ============================================================================
// OUTPUTS
// ============================================================================

output zoneId string = dnsZone.id
output zoneName string = dnsZone.name
output nameServers array = dnsZone.properties.nameServers
